<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>NetLens.Infrastructure</AssemblyName>
    <RootNamespace>NetLens.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NetLens.Application\NetLens.Application.csproj" />
    <ProjectReference Include="..\NetLens.Database\NetLens.Database.csproj" />
  </ItemGroup>
</Project>
